"API_key_list":
  - ""
  - ""
"seed_file_path" : "../seed_data/"
"all_file_path" : "../all_data/"
"ke_entity_extratction_prompt" : "../prompt/kg_exploration/entity_extraction"
"ke_relation_extratction_prompt" : "../prompt/kg_exploration/relation_extraction"
"ke_entity_labeling_prompt" : "../prompt/kg_exploration/entity_type_label"
"ke_entity_type_fusion_prompt" : "../prompt/kg_exploration/entity_type_fusion"
"ke_relation_type_fusion_prompt" : "../prompt/kg_exploration/relation_type_fusion"
"kc_entity_extratction_prompt" : "../prompt/kg_construction/entity_extraction"
"kc_relation_extratction_prompt" : "../prompt/kg_construction/relation_extraction"
"save_ke_entity_path" : "../output/kg_exploration/entity.csv"
"save_ke_relation_path" : "../output/kg_exploration/relation.csv"
"save_ke_entity_label_path" : "../output/kg_exploration/entity_label.csv"
"save_ke_entity_type_path" : "../output/kg_exploration/entity_type.csv"
"save_ke_relation_type_path" : "../output/kg_exploration/relation_type.csv"
"save_kc_entity_path" : "../output/kg_construction/entity.csv"
"save_kc_relation_path" : "../output/kg_construction/relation.csv"
"save_kr_initial_schema_path" : "../output/kg_filtering/initial_schema.csv"
"save_kr_filter_schema_path" : "../output/kg_filtering/filter_schema.csv"
"save_kr_filter_kg_path" : "../output/kg_filtering/filter_kg.csv"